"""init

Revision ID: a1289ecd22f0
Revises: 
Create Date: 2026-06-19 15:45:46.474859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1289ecd22f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b2c_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=True),
    sa.Column('originator_conversation_id', sa.String(length=100), nullable=False),
    sa.Column('receiver_phone', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_code', sa.String(length=10), nullable=True),
    sa.Column('result_desc', sa.String(length=255), nullable=True),
    sa.Column('transaction_receipt', sa.String(length=50), nullable=True),
    sa.Column('receiver_party_public_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_b2c_transactions_conversation_id'), 'b2c_transactions', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_b2c_transactions_originator_conversation_id'), 'b2c_transactions', ['originator_conversation_id'], unique=True)
    op.create_table('c2b_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('trans_id', sa.String(length=50), nullable=False),
    sa.Column('trans_time', sa.String(length=20), nullable=False),
    sa.Column('trans_amount', sa.Integer(), nullable=False),
    sa.Column('business_shortcode', sa.String(length=20), nullable=False),
    sa.Column('bill_ref_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('org_account_balance', sa.String(length=50), nullable=True),
    sa.Column('third_party_trans_id', sa.String(length=50), nullable=True),
    sa.Column('msisdn', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_c2b_transactions_trans_id'), 'c2b_transactions', ['trans_id'], unique=True)
    op.create_table('stk_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_request_id', sa.String(length=100), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('account_reference', sa.String(length=50), nullable=False),
    sa.Column('transaction_desc', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('result_code', sa.String(length=10), nullable=True),
    sa.Column('result_desc', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stk_transactions_checkout_request_id'), 'stk_transactions', ['checkout_request_id'], unique=True)
    op.create_index(op.f('ix_stk_transactions_merchant_request_id'), 'stk_transactions', ['merchant_request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stk_transactions_merchant_request_id'), table_name='stk_transactions')
    op.drop_index(op.f('ix_stk_transactions_checkout_request_id'), table_name='stk_transactions')
    op.drop_table('stk_transactions')
    op.drop_index(op.f('ix_c2b_transactions_trans_id'), table_name='c2b_transactions')
    op.drop_table('c2b_transactions')
    op.drop_index(op.f('ix_b2c_transactions_originator_conversation_id'), table_name='b2c_transactions')
    op.drop_index(op.f('ix_b2c_transactions_conversation_id'), table_name='b2c_transactions')
    op.drop_table('b2c_transactions')
    # ### end Alembic commands ###
